### PR TITLE
Kinematic Character

### PR DESCRIPTION
**Pull request by RameshRavone**

### CODE REVIEW

**Comment by RameshRavone** [comment]
Will do, thanks again I'll update soon.

**Comment by RameshRavone** [comment]
@karroffel is it ok if I where to use the clang-format file from godot engine.

**Comment by karroffel** [comment]
Yes ^^

**Comment by RameshRavone** [comment]
In case you didn't notice, The changes were committed.

**Comment by karroffel** [comment]
Ah nice, didn't test it yet, hope to do that tonight

**Comment by karroffel** [comment]
I think you forgot to submit the SConstruct file

**Comment by RameshRavone** [comment]
@karroffel made a PR, sorry about that.

**Pull request merged**
